In [2]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])

In [5]:
print(a1)

[1 2 3]


In [6]:
type(a1)

numpy.ndarray

In [7]:
a1.shape

(3,)

In [8]:
a2 = np.array([[1, 2, 3], [4, 5, 6 ]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(type(a2), a2.shape)

<class 'numpy.ndarray'> (2, 3)


In [11]:
a3 = np.array([[1, 2, 3]])
print(a3)

[[1 2 3]]


In [12]:
print(type(a3), a3.shape)

<class 'numpy.ndarray'> (1, 3)


In [14]:
# 각 배열의 차원

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
2


In [15]:
# arange 함수를 이용하면 쉽게 배열 구조 생성 가능
# np.arange(x) > 0부터 x-1까지의 값을 순차적 배열의 데이터 값으로 생성 가능

a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
a = np.arange(1, 20, 3) # (x, y, z) : x 갑부터 y-1까지 z만큼 증가하는 배열 생성
print(a)

[ 1  4  7 10 13 16 19]


## numpy 배열 초기화 : zeros, ones 사용

In [17]:
zero_a = np.zeros((2, 5))
print(zero_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
one_a = np.ones((3, 4))
print(one_a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# 이미 생성된 배열의 구조와 동일한 구조 유지한 상태에서 1로 채워진 배열로 초기화해서 생성
one_b = np.ones_like(zero_a)
print(one_b, zero_a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
full_a = np.full((4, 3), 9)
print(full_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [22]:
type(full_a)

numpy.ndarray

In [23]:
random_a = np.random.random((3, 4))
print(random_a)

[[0.3864326  0.51532106 0.96054456 0.77754094]
 [0.14235029 0.47863063 0.91637695 0.12298657]
 [0.77369401 0.12465428 0.76416872 0.61632336]]


In [24]:
# 대각행렬 생성
eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 배열의 차원과 크기 변경 > reshape

In [25]:
array1 = np.arange(12)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
array2 = array1.reshape(3, 4)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
array3 = array1.reshape(3, 4, order='F')
print(array3)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [29]:
# reshape시 -1을 입력하면 원래 배열과 호환되는 크기로 자동 변환
array1 = np.arange(10)
array2 = array1.reshape(-1, 5)  # array1과 호환될 수 있는 2차원 배열로 변환하되, 고정된 5개의 컬럼에 맞는 행을 자동으로 새롭게 생성

print(array2)
print(array2.ndim)
print(array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
(2, 5)


In [30]:
array1 = np.arange(12)
array2 = array1.reshape(2, 3, 2, order='F')

print(array2)
print(array2.ndim)
print(array2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
3
(2, 3, 2)


## numpy flatten 함수의 1차원 변형

In [31]:
array3 = array2.flatten()
print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


## numpy 배열 데이터 추출하기

In [32]:
array1 = np.arange(1, 10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [33]:
value1 = array1[2]
value2 = array1[-2]

print(value1, value2)

3 8


In [34]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
value1 = array2[0, 0]
value2 = array2[-1, -1]
value3 = array2[-1, -2]

print(value1, value2, value3)

1 9 8


In [36]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print(array2[0:2, 0:2])

[[1 2]
 [4 5]]


In [39]:
print(array2[1:3, 0:3])

[[4 5 6]
 [7 8 9]]


In [40]:
print(array2[:2, 1:])

[[2 3]
 [5 6]]


In [41]:
print(array2[:2, 0])

[1 4]


## 선형대수 기본연산

In [42]:
# 행렬곱
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10],
                   [10, 11]])

In [43]:
dot_array = np.dot(array1, array2)
dot_array

array([[ 55,  61],
       [133, 148]])

In [47]:
# 전치 행렬
print(array1)
print(np.transpose(array1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 기술 통계

In [48]:
# 배열 데이터 개수 계산

x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
print(len(x))

20


In [50]:
# 평균
np.mean(x)

9.5

In [51]:
# 분산
np.var(x)

33.25

In [52]:
# 표준편차
np.std(x)

5.766281297335398

In [53]:
# 최대
np.max(x)

19

In [54]:
# 최소
np.min(x)

0

In [55]:
# 중앙값
np.median(x)

9.5

In [58]:
# 사분위수
np.percentile(x, 25) # 1사분위수

4.75

In [59]:
np.percentile(x, 50) # 2 사분위수

9.5

In [60]:
np.percentile(x, 75) # 3사분위수

14.25