## Numpy

배열 연산 속도가 매우 빠르다

In [1]:
import numpy as np

In [2]:
arr = np.array([2, 6, 5, 9], float)
arr

array([2., 6., 5., 9.])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.tolist()

[2.0, 6.0, 5.0, 9.0]

In [5]:
list(arr)

[2.0, 6.0, 5.0, 9.0]

* 새 객체 생성 - copy 사용

In [6]:
arr = np.array([1, 2, 3], float)
arr1 = arr
arr2 = arr.copy()

In [7]:
arr[0]

1.0

In [8]:
arr

array([1., 2., 3.])

In [9]:
arr1

array([1., 2., 3.])

In [10]:
arr2

array([1., 2., 3.])

* 배열을 단일 값으로 채우기 - ㄹill

In [11]:
arr = np.array([10, 20, 33], float)
arr

array([10., 20., 33.])

In [12]:
arr.fill(1)
arr

array([1., 1., 1.])

* 배열 랜덤 생성 - submodule 사용

In [13]:
np.random.permutation(3)

array([1, 0, 2])

* normal 함수는 정규 분포를 따르는 숫자열 만듦

In [14]:
np.random.normal(0, 1, 5)

array([-0.80584381,  0.03238358,  1.23480053,  0.06256708,  1.34485446])

* random 함수는 균등 분포를 따르며, 0과 1 사이의 값을 반환함

In [15]:
np.random.random(5)

array([0.18073154, 0.31264569, 0.3401228 , 0.31808399, 0.64393296])

* 단위 행렬(identity matrix) 생성하기

In [16]:
np.identity(5, dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* eye 함수는 K번째 대각(diagonal)이 1인 행렬을 반환

In [17]:
np.eye(3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

* 배열 생성 시 가장 많이 사용하는 함수는 zeros와 ones
* 차원과 타입을 인자로 넘겨 각각 0과 1로 채워진 배열을 만듦

In [18]:
np.ones((2, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

* zeros_like, ones_like 함수는 주어진 배열과 동일한 차원과 타입을 가지는 새로운 배열을 만듦

In [20]:
arr = np.array([[13, 32, 31], [64, 25, 76]], float)

In [21]:
np.zeros_like(arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones_like(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

* 2차원 배열을 만드는 다른 방법 - vstack 함수 (여러 개의 1차원 배열을 수직 방향으로 합치기)

In [23]:
arr1 = np.array([1, 3, 2])
arr2 = np.array([3, 4, 6])
np.vstack([arr1, arr2])

array([[1, 3, 2],
       [3, 4, 6]])

* random 서브모듈 - 분포를 이용해 2차원 배열을 만들 수 있음. 0과 1 사이의 균등 분포로부터 2*3 배열을 만들 수 있음

In [24]:
np.random.rand(2, 3)

array([[0.46988854, 0.71428138, 0.34021775],
       [0.48977569, 0.46203553, 0.94942   ]])

* 다변량 정규 분포

In [25]:
np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[5,])   # 리스트 [10, 0]은 평균 벡터, [[3, 1], [1, 4]]는 공분산 행렬, 5는 생성될 샘플 개수

array([[ 8.77392349,  0.4879126 ],
       [ 8.18152964, -0.53052327],
       [10.8551736 ,  2.73772262],
       [10.50577809,  2.50596478],
       [ 8.47210179, -1.25613635]])

## 배열 조작

In [26]:
arr = np.array([2., 6., 5., 5.])
arr[:3]

array([2., 6., 5.])

* unique() - 중복이 제거된 유일한 값을 선택

In [27]:
np.unique(arr)

array([2., 5., 6.])

* sort - 배열의 값 정렬
* argsort - 배열 정렬 후 인덱스 반환

In [28]:
np.sort(arr)

array([2., 5., 5., 6.])

In [29]:
np.argsort(arr)

array([0, 2, 3, 1])

* shuffle() - 배열의 요소를 무작위로 재배열

In [30]:
np.random.shuffle(arr)

In [31]:
arr

array([5., 5., 6., 2.])

* numpy는 배열을 비교하는 array_equal 내장 함수를 제공함

In [32]:
np.array_equal(arr, np.array([1, 3, 2]))

False

* 다차원 배열의 리스트 표현하기

In [33]:
matrix = np.array([[4., 5., 6.], [2, 3, 6]], float)
matrix

array([[4., 5., 6.],
       [2., 3., 6.]])

In [34]:
matrix[0, 0]

4.0

* slicing - 잘라낼 부분의 시작과 끝 인덱스 값 사이에 콜론(:) 심볼을 넣어서 각 차원별로 적용하기

In [35]:
arr = np.array([[4., 5., 6.], [2., 3., 6.]], float)
arr[1:2, 2:3]

array([[6.]])

* 해당 축을 따라 전체 요소가 고려됨

In [36]:
arr[1, :]

array([2., 3., 6.])

In [37]:
arr[:, 2]

array([6., 6.])

In [38]:
arr[-1:, -2:]

array([[3., 6.]])

* flatten 함수를 이용하면 다차원 배열에서 1차원 배열을 생성할 수 있음

In [39]:
arr = np.array([[10, 29, 23], [24, 25, 46]], float)
arr

array([[10., 29., 23.],
       [24., 25., 46.]])

In [40]:
arr.flatten()

array([10., 29., 23., 24., 25., 46.])

* shape - 배열의 크기
* dtype - 배열에 저장된 값의 타입 반환

In [41]:
arr.shape

(2, 3)

In [42]:
arr.dtype

dtype('float64')

* 데이터 타입 및 배열의 타입 변환 - astype()

In [43]:
int_arr = matrix.astype(np.int32)
int_arr.dtype

dtype('int32')

* len - 배열의 첫 번째 차원의 길이 반환

In [44]:
arr = np.array([[4., 5., 6.], [2., 3., 6.]], float)
len(arr)

2

* in - 배열이 해당 값을 포함하는지 체크

In [45]:
arr = np.array([[4., 5., 6.], [2., 3., 6.]], float)
2 in arr

True

In [46]:
0 in arr

False

* reshape - 배열의 요소를 다른 차원으로 재배열해 모양을 바꿀 수 있음

In [47]:
arr = np.array(range(8), float)
arr

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [48]:
arr = arr.reshape((4, 2))
arr

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]])

* 전치 행렬(transpose matrix) - transpose 함수로, 배열의 두 차원을 바꿔 구할 수 있음

In [49]:
arr = np.array(range(6), float).reshape((2, 3))
arr

array([[0., 1., 2.],
       [3., 4., 5.]])

In [50]:
arr.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

* 배열의 T 속성 - 전치 행렬 구할 수 있음

In [51]:
matrix = np.arange(15).reshape((3, 5))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
matrix.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

* 배열의 요소를 재배열 - newaxis

In [53]:
arr = np.array([14, 32, 13], float)
arr

array([14., 32., 13.])

In [54]:
arr[:, np.newaxis]

array([[14.],
       [32.],
       [13.]])

In [55]:
arr[:, np.newaxis].shape

(3, 1)

In [56]:
arr[np.newaxis, :]

array([[14., 32., 13.]])

In [57]:
arr[np.newaxis, :].shape

(1, 3)

* 배열을 결합하는 함수 - concatenate
* 1차원 배열을 결합할 경우 결합될 배열들의 튜플(tuple)을 만들어 함수의 인자로 넘긴다

In [58]:
arr1 = np.array([10, 22], float)
arr2 = np.array([31, 43, 54, 61], float)
arr3 = np.array([71, 82, 29], float)
np.concatenate((arr1, arr2, arr3))

array([10., 22., 31., 43., 54., 61., 71., 82., 29.])

* tostring() - 배열을 바이너리 문자열로 변환
* fromstring() - 문자열을 배열로 변환

In [59]:
arr = np.array([10, 20, 30], float)
str = arr.tostring()
str

/var/folders/_p/x_57820s1b15kl1dk8sw72kc0000gn/T/ipykernel_3992/380517963.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  str = arr.tostring()


b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x004@\x00\x00\x00\x00\x00\x00>@'

In [60]:
np.fromstring(str)

/var/folders/_p/x_57820s1b15kl1dk8sw72kc0000gn/T/ipykernel_3992/1562618676.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(str)


array([10., 20., 30.])