## Numpy

배열 연산 속도가 매우 빠르다

In [2]:
import numpy as np

In [2]:
arr = np.array([2, 6, 5, 9], float)
arr

array([2., 6., 5., 9.])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.tolist()

[2.0, 6.0, 5.0, 9.0]

In [5]:
list(arr)

[2.0, 6.0, 5.0, 9.0]

* 새 객체 생성 - copy 사용

In [6]:
arr = np.array([1, 2, 3], float)
arr1 = arr
arr2 = arr.copy()

In [7]:
arr[0]

1.0

In [8]:
arr

array([1., 2., 3.])

In [9]:
arr1

array([1., 2., 3.])

In [10]:
arr2

array([1., 2., 3.])

* 배열을 단일 값으로 채우기 - ㄹill

In [11]:
arr = np.array([10, 20, 33], float)
arr

array([10., 20., 33.])

In [12]:
arr.fill(1)
arr

array([1., 1., 1.])

* 배열 랜덤 생성 - submodule 사용

In [13]:
np.random.permutation(3)

array([1, 0, 2])

* normal 함수는 정규 분포를 따르는 숫자열 만듦

In [14]:
np.random.normal(0, 1, 5)

array([-0.80584381,  0.03238358,  1.23480053,  0.06256708,  1.34485446])

* random 함수는 균등 분포를 따르며, 0과 1 사이의 값을 반환함

In [15]:
np.random.random(5)

array([0.18073154, 0.31264569, 0.3401228 , 0.31808399, 0.64393296])

* 단위 행렬(identity matrix) 생성하기

In [16]:
np.identity(5, dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* eye 함수는 K번째 대각(diagonal)이 1인 행렬을 반환

In [17]:
np.eye(3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

* 배열 생성 시 가장 많이 사용하는 함수는 zeros와 ones
* 차원과 타입을 인자로 넘겨 각각 0과 1로 채워진 배열을 만듦

In [18]:
np.ones((2, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

* zeros_like, ones_like 함수는 주어진 배열과 동일한 차원과 타입을 가지는 새로운 배열을 만듦

In [20]:
arr = np.array([[13, 32, 31], [64, 25, 76]], float)

In [21]:
np.zeros_like(arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones_like(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

* 2차원 배열을 만드는 다른 방법 - vstack 함수 (여러 개의 1차원 배열을 수직 방향으로 합치기)

In [23]:
arr1 = np.array([1, 3, 2])
arr2 = np.array([3, 4, 6])
np.vstack([arr1, arr2])

array([[1, 3, 2],
       [3, 4, 6]])

* random 서브모듈 - 분포를 이용해 2차원 배열을 만들 수 있음. 0과 1 사이의 균등 분포로부터 2*3 배열을 만들 수 있음

In [24]:
np.random.rand(2, 3)

array([[0.46988854, 0.71428138, 0.34021775],
       [0.48977569, 0.46203553, 0.94942   ]])

* 다변량 정규 분포

In [25]:
np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[5,])   # 리스트 [10, 0]은 평균 벡터, [[3, 1], [1, 4]]는 공분산 행렬, 5는 생성될 샘플 개수

array([[ 8.77392349,  0.4879126 ],
       [ 8.18152964, -0.53052327],
       [10.8551736 ,  2.73772262],
       [10.50577809,  2.50596478],
       [ 8.47210179, -1.25613635]])

## 배열 조작

In [26]:
arr = np.array([2., 6., 5., 5.])
arr[:3]

array([2., 6., 5.])

* unique() - 중복이 제거된 유일한 값을 선택

In [27]:
np.unique(arr)

array([2., 5., 6.])

* sort - 배열의 값 정렬
* argsort - 배열 정렬 후 인덱스 반환

In [28]:
np.sort(arr)

array([2., 5., 5., 6.])

In [29]:
np.argsort(arr)

array([0, 2, 3, 1])

* shuffle() - 배열의 요소를 무작위로 재배열

In [30]:
np.random.shuffle(arr)

In [31]:
arr

array([5., 5., 6., 2.])

* numpy는 배열을 비교하는 array_equal 내장 함수를 제공함

In [32]:
np.array_equal(arr, np.array([1, 3, 2]))

False

* 다차원 배열의 리스트 표현하기

In [33]:
matrix = np.array([[4., 5., 6.], [2, 3, 6]], float)
matrix

array([[4., 5., 6.],
       [2., 3., 6.]])

In [34]:
matrix[0, 0]

4.0

* slicing - 잘라낼 부분의 시작과 끝 인덱스 값 사이에 콜론(:) 심볼을 넣어서 각 차원별로 적용하기

In [35]:
arr = np.array([[4., 5., 6.], [2., 3., 6.]], float)
arr[1:2, 2:3]

array([[6.]])

* 해당 축을 따라 전체 요소가 고려됨

In [36]:
arr[1, :]

array([2., 3., 6.])

In [37]:
arr[:, 2]

array([6., 6.])

In [38]:
arr[-1:, -2:]

array([[3., 6.]])

* flatten 함수를 이용하면 다차원 배열에서 1차원 배열을 생성할 수 있음

In [39]:
arr = np.array([[10, 29, 23], [24, 25, 46]], float)
arr

array([[10., 29., 23.],
       [24., 25., 46.]])

In [40]:
arr.flatten()

array([10., 29., 23., 24., 25., 46.])

* shape - 배열의 크기
* dtype - 배열에 저장된 값의 타입 반환

In [41]:
arr.shape

(2, 3)

In [42]:
arr.dtype

dtype('float64')

* 데이터 타입 및 배열의 타입 변환 - astype()

In [43]:
int_arr = matrix.astype(np.int32)
int_arr.dtype

dtype('int32')

* len - 배열의 첫 번째 차원의 길이 반환

In [44]:
arr = np.array([[4., 5., 6.], [2., 3., 6.]], float)
len(arr)

2

* in - 배열이 해당 값을 포함하는지 체크

In [45]:
arr = np.array([[4., 5., 6.], [2., 3., 6.]], float)
2 in arr

True

In [46]:
0 in arr

False

* reshape - 배열의 요소를 다른 차원으로 재배열해 모양을 바꿀 수 있음

In [47]:
arr = np.array(range(8), float)
arr

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [48]:
arr = arr.reshape((4, 2))
arr

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]])

* 전치 행렬(transpose matrix) - transpose 함수로, 배열의 두 차원을 바꿔 구할 수 있음

In [49]:
arr = np.array(range(6), float).reshape((2, 3))
arr

array([[0., 1., 2.],
       [3., 4., 5.]])

In [50]:
arr.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

* 배열의 T 속성 - 전치 행렬 구할 수 있음

In [51]:
matrix = np.arange(15).reshape((3, 5))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
matrix.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

* 배열의 요소를 재배열 - newaxis

In [53]:
arr = np.array([14, 32, 13], float)
arr

array([14., 32., 13.])

In [54]:
arr[:, np.newaxis]

array([[14.],
       [32.],
       [13.]])

In [55]:
arr[:, np.newaxis].shape

(3, 1)

In [56]:
arr[np.newaxis, :]

array([[14., 32., 13.]])

In [57]:
arr[np.newaxis, :].shape

(1, 3)

* 배열을 결합하는 함수 - concatenate
* 1차원 배열을 결합할 경우 결합될 배열들의 튜플(tuple)을 만들어 함수의 인자로 넘긴다

In [58]:
arr1 = np.array([10, 22], float)
arr2 = np.array([31, 43, 54, 61], float)
arr3 = np.array([71, 82, 29], float)
np.concatenate((arr1, arr2, arr3))

array([10., 22., 31., 43., 54., 61., 71., 82., 29.])

* tostring() - 배열을 바이너리 문자열로 변환
* fromstring() - 문자열을 배열로 변환

In [59]:
arr = np.array([10, 20, 30], float)
str = arr.tostring()
str

/var/folders/_p/x_57820s1b15kl1dk8sw72kc0000gn/T/ipykernel_3992/380517963.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  str = arr.tostring()


b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x004@\x00\x00\x00\x00\x00\x00>@'

In [60]:
np.fromstring(str)

/var/folders/_p/x_57820s1b15kl1dk8sw72kc0000gn/T/ipykernel_3992/1562618676.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(str)


array([10., 20., 30.])

### 배열 연산

* numpy은 배열의 기본 수학 연산을 지원함. 예를 들면 다음과 같음.

In [61]:
arr1 = np.array([1, 2, 3], float)
arr2 = np.array([1, 2, 3], float)
arr1 + arr2

array([2., 4., 6.])

In [62]:
arr1 - arr2

array([0., 0., 0.])

In [63]:
arr1 * arr2

array([1., 4., 9.])

In [64]:
arr2 / arr1

array([1., 1., 1.])

In [65]:
arr1 % arr2

array([0., 0., 0.])

In [66]:
arr2 ** arr1

array([ 1.,  4., 27.])

* 파이썬의 리스트와 달리 배열은 조건을 사용해 쿼리(query)할 수 있음

In [67]:
arr = np.array([[1, 2], [5, 9]], float)
arr >= 7

array([[False, False],
       [False,  True]])

In [68]:
arr[arr >= 7]

array([9.])

* 다중 논리식 사용 가능

In [69]:
arr[np.logical_and(arr > 5, arr < 11)]

array([9.])

* take() 함수 - 괄호 선택 방식과 동일한 것으로, 정수 인덱스 배열을 입력 받음

In [70]:
arr1 = np.array([7, 6, 6, 9], float)
arr2 = np.array([1, 0, 1, 3, 3, 1], int)
arr1.take(arr2)

array([6., 7., 6., 9., 9., 6.])

* put() - 인덱스와 배열의 값을 입력받아 해당 인덱스 위치에 값을 넣어줌

In [71]:
arr1 = np.array([2, 1, 6, 2, 1, 9], float)
arr2 = np.array([3, 10, 2], float)
arr1.put([1, 4], arr2)
arr1

array([ 2.,  3.,  6.,  2., 10.,  9.])

### 선행대수 연산

* 내적 구하기 - np.dot()

In [72]:
X = np.arange(15). reshape((3, 5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
X.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [74]:
np.dot(X.T, X)   # X^T * X

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

* 내적(inner product)과 점곱(dot product)은 동일함

In [3]:
arr1 = np.array([12, 43, 10], float)
arr2 = np.array([21, 42, 14], float)
np.outer(arr1, arr2)

array([[ 252.,  504.,  168.],
       [ 903., 1806.,  602.],
       [ 210.,  420.,  140.]])

In [4]:
np.inner(arr1, arr2)

2198.0

In [5]:
np.cross(arr1, arr2)

array([ 182.,   42., -399.])

* numpy - linalg 서브모듈은 행렬에 대한 선형대수 함수를 포함함

In [7]:
matrix = np.array([[74, 22, 10], [92, 31, 17], [21, 22, 12]], float)

In [8]:
matrix

array([[74., 22., 10.],
       [92., 31., 17.],
       [21., 22., 12.]])

* inv - 역행렬 구하는 함수

In [9]:
inv_matrix = np.linalg.inv(matrix)

In [10]:
inv_matrix

array([[ 0.00070126,  0.01542777, -0.02244039],
       [ 0.26192146, -0.23772791,  0.11851332],
       [-0.48141655,  0.4088359 , -0.09467041]])

* 행렬의 고윳값(eigenvalue)과 고유 벡터(eigenvector) 구하기

In [11]:
vals, vacs = np.linalg.eig(matrix)

In [12]:
vals

array([107.99587441,  11.33411853,  -2.32999294])

In [13]:
vacs

array([[-0.57891525, -0.21517959,  0.06319955],
       [-0.75804695,  0.17632618, -0.58635713],
       [-0.30036971,  0.96052424,  0.80758352]])

In [14]:
arr = np.random.rand(8, 4)

In [15]:
arr

array([[0.44347317, 0.50439049, 0.21175233, 0.4251421 ],
       [0.67510986, 0.93947646, 0.82882205, 0.64934505],
       [0.45059898, 0.60620284, 0.06763268, 0.96533543],
       [0.50091805, 0.74199821, 0.97024104, 0.75620161],
       [0.35116738, 0.00989978, 0.00966443, 0.66184534],
       [0.94751718, 0.96102327, 0.69328027, 0.99411443],
       [0.22893528, 0.05110564, 0.98926242, 0.71524372],
       [0.35087272, 0.00940034, 0.68108179, 0.73818739]])

In [16]:
arr.mean()

0.5665388038046587

In [17]:
np.mean(arr)

0.5665388038046587

In [18]:
arr.sum()

18.12924172174908

### Pandas 모듈 이해하기

In [20]:
import pandas as pd

In [21]:
obj = pd.Series([3, 5, -2, 1])

In [22]:
obj

0    3
1    5
2   -2
3    1
dtype: int64

In [23]:
obj.values

array([ 3,  5, -2,  1])

In [24]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
obj * 2

0     6
1    10
2    -4
3     2
dtype: int64

In [26]:
obj[obj > 2]

0    3
1    5
dtype: int64

In [27]:
data = {'a': 30, 'b': 70, 'c': 160, 'd': 5}
obj = pd.Series(data)
obj

a     30
b     70
c    160
d      5
dtype: int64

In [28]:
index = ['a', 'b', 'c', 'd', 'g']
obj = pd.Series(data, index = index)
obj

a     30.0
b     70.0
c    160.0
d      5.0
g      NaN
dtype: float64

In [29]:
pd.isnull(obj)

a    False
b    False
c    False
d    False
g     True
dtype: bool

In [30]:
pd.notnull(obj)

a     True
b     True
c     True
d     True
g    False
dtype: bool

In [33]:
data = pd.read_csv('./../../data/ad.data', header=None)

/opt/homebrew/Caskroom/miniforge/base/envs/pandas_info/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [34]:
data

0     1       2    3     4     5     6     7     8     9     ...  1549  \
0      125   125     1.0    1     0     0     0     0     0     0  ...     0   
1       57   468  8.2105    1     0     0     0     0     0     0  ...     0   
2       33   230  6.9696    1     0     0     0     0     0     0  ...     0   
3       60   468     7.8    1     0     0     0     0     0     0  ...     0   
4       60   468     7.8    1     0     0     0     0     0     0  ...     0   
...    ...   ...     ...  ...   ...   ...   ...   ...   ...   ...  ...   ...   
3274   170    94  0.5529    0     0     0     0     0     0     0  ...     0   
3275   101   140  1.3861    1     0     0     0     0     0     0  ...     0   
3276    23   120  5.2173    1     0     0     0     0     0     0  ...     0   
3277     ?     ?       ?    1     0     0     0     0     0     0  ...     0   
3278    40    40     1.0    1     0     0     0     0     0     0  ...     0   

      1550  1551  1552  1553  1554  1555  1556  1557    1558  
0        0     0     0     0     0     0     0     0     ad.  
1        0     0     0     0     0     0     0     0     ad.  
2        0     0     0     0     0     0     0     0     ad.  
3        0     0     0     0     0     0     0     0     ad.  
4        0     0     0     0     0     0     0     0     ad.  
...    ...   ...   ...   ...   ...   ...   ...   ...     ...  
3274     0     0     0     0     0     0     0     0  nonad.  
3275     0     0     0     0     0     0     0     0  nonad.  
3276     0     0     0     0     0     0     0     0  nonad.  
3277     0     0     0     0     0     0     0     0  nonad.  
3278     0     0     0     0     0     0     0     0  nonad.  

[3279 rows x 1559 columns]

In [35]:
data.describe()

4            5            6            7            8     \
count  3279.000000  3279.000000  3279.000000  3279.000000  3279.000000   
mean      0.004270     0.011589     0.004575     0.003355     0.003965   
std       0.065212     0.107042     0.067491     0.057831     0.062850   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              9            10           11           12           13    ...  \
count  3279.000000  3279.000000  3279.000000  3279.000000  3279.000000  ...   
mean      0.011589     0.003355     0.004880     0.009149     0.004575  ...   
std       0.107042     0.057831     0.069694     0.095227     0.067491  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              1548         1549         1550         1551         1552  \
count  3279.000000  3279.000000  3279.000000  3279.000000  3279.000000   
mean      0.006099     0.004575     0.003660     0.002440     0.003050   
std       0.077872     0.067491     0.060393     0.049341     0.055148   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              1553         1554         1555         1556         1557  
count  3279.000000  3279.000000  3279.000000  3279.000000  3279.000000  
mean      0.006404     0.012809     0.013419     0.009759     0.001525  
std       0.079783     0.112466     0.115077     0.098320     0.039026  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 1554 columns]

In [36]:
data.columns

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558],
           dtype='int64', length=1559)

In [37]:
data.dtypes

0       object
1       object
2       object
3       object
4        int64
         ...  
1554     int64
1555     int64
1556     int64
1557     int64
1558    object
Length: 1559, dtype: object

In [38]:
data[1]

0        125
1        468
2        230
3        468
4        468
        ... 
3274      94
3275     140
3276     120
3277       ?
3278      40
Name: 1, Length: 3279, dtype: object

In [39]:
data[[1, 20]]

1   20
0      125   0
1      468   0
2      230   0
3      468   0
4      468   0
...    ...  ..
3274    94   0
3275   140   0
3276   120   0
3277     ?   0
3278    40   0

[3279 rows x 2 columns]

In [40]:
data[1].head()

0     125
1     468
2     230
3     468
4     468
Name: 1, dtype: object

In [41]:
data[1].tail()

3274      94
3275     140
3276     120
3277       ?
3278      40
Name: 1, dtype: object

In [46]:
data.iloc[:3]

0     1       2    3     4     5     6     7     8     9     ...  1549  \
0   125   125     1.0    1     0     0     0     0     0     0  ...     0   
1    57   468  8.2105    1     0     0     0     0     0     0  ...     0   
2    33   230  6.9696    1     0     0     0     0     0     0  ...     0   

   1550  1551  1552  1553  1554  1555  1556  1557  1558  
0     0     0     0     0     0     0     0     0   ad.  
1     0     0     0     0     0     0     0     0   ad.  
2     0     0     0     0     0     0     0     0   ad.  

[3 rows x 1559 columns]

In [47]:
data.loc[:3]

0     1       2    3     4     5     6     7     8     9     ...  1549  \
0   125   125     1.0    1     0     0     0     0     0     0  ...     0   
1    57   468  8.2105    1     0     0     0     0     0     0  ...     0   
2    33   230  6.9696    1     0     0     0     0     0     0  ...     0   
3    60   468     7.8    1     0     0     0     0     0     0  ...     0   

   1550  1551  1552  1553  1554  1555  1556  1557  1558  
0     0     0     0     0     0     0     0     0   ad.  
1     0     0     0     0     0     0     0     0   ad.  
2     0     0     0     0     0     0     0     0   ad.  
3     0     0     0     0     0     0     0     0   ad.  

[4 rows x 1559 columns]

In [48]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
3274    False
3275    False
3276    False
3277     True
3278    False
Length: 3279, dtype: bool

In [49]:
data[1558].drop_duplicates()

0         ad.
459    nonad.
Name: 1558, dtype: object