## Numpy

배열 연산 속도가 매우 빠르다

In [1]:
import numpy as np

In [2]:
arr = np.array([2, 6, 5, 9], float)
arr

array([2., 6., 5., 9.])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.tolist()

[2.0, 6.0, 5.0, 9.0]

In [5]:
list(arr)

[2.0, 6.0, 5.0, 9.0]

* 새 객체 생성 - copy 사용

In [6]:
arr = np.array([1, 2, 3], float)
arr1 = arr
arr2 = arr.copy()

In [7]:
arr[0]

1.0

In [8]:
arr

array([1., 2., 3.])

In [9]:
arr1

array([1., 2., 3.])

In [10]:
arr2

array([1., 2., 3.])

* 배열을 단일 값으로 채우기 - ㄹill

In [11]:
arr = np.array([10, 20, 33], float)
arr

array([10., 20., 33.])

In [12]:
arr.fill(1)
arr

array([1., 1., 1.])

* 배열 랜덤 생성 - submodule 사용

In [13]:
np.random.permutation(3)

array([1, 0, 2])

* normal 함수는 정규 분포를 따르는 숫자열 만듦

In [14]:
np.random.normal(0, 1, 5)

array([-0.80584381,  0.03238358,  1.23480053,  0.06256708,  1.34485446])

* random 함수는 균등 분포를 따르며, 0과 1 사이의 값을 반환함

In [15]:
np.random.random(5)

array([0.18073154, 0.31264569, 0.3401228 , 0.31808399, 0.64393296])

* 단위 행렬(identity matrix) 생성하기

In [16]:
np.identity(5, dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* eye 함수는 K번째 대각(diagonal)이 1인 행렬을 반환

In [17]:
np.eye(3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

* 배열 생성 시 가장 많이 사용하는 함수는 zeros와 ones
* 차원과 타입을 인자로 넘겨 각각 0과 1로 채워진 배열을 만듦

In [18]:
np.ones((2, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

* zeros_like, ones_like 함수는 주어진 배열과 동일한 차원과 타입을 가지는 새로운 배열을 만듦

In [20]:
arr = np.array([[13, 32, 31], [64, 25, 76]], float)

In [21]:
np.zeros_like(arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones_like(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

* 2차원 배열을 만드는 다른 방법 - vstack 함수 (여러 개의 1차원 배열을 수직 방향으로 합치기)

In [23]:
arr1 = np.array([1, 3, 2])
arr2 = np.array([3, 4, 6])
np.vstack([arr1, arr2])

array([[1, 3, 2],
       [3, 4, 6]])

* random 서브모듈 - 분포를 이용해 2차원 배열을 만들 수 있음. 0과 1 사이의 균등 분포로부터 2*3 배열을 만들 수 있음

In [24]:
np.random.rand(2, 3)

array([[0.46988854, 0.71428138, 0.34021775],
       [0.48977569, 0.46203553, 0.94942   ]])

* 다변량 정규 분포

In [25]:
np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[5,])   # 리스트 [10, 0]은 평균 벡터, [[3, 1], [1, 4]]는 공분산 행렬, 5는 생성될 샘플 개수

array([[ 8.77392349,  0.4879126 ],
       [ 8.18152964, -0.53052327],
       [10.8551736 ,  2.73772262],
       [10.50577809,  2.50596478],
       [ 8.47210179, -1.25613635]])

## 배열 조작

In [26]:
arr = np.array([2., 6., 5., 5.])
arr[:3]

array([2., 6., 5.])

* unique() - 중복이 제거된 유일한 값을 선택

In [27]:
np.unique(arr)

array([2., 5., 6.])

* sort - 배열의 값 정렬
* argsort - 배열 정렬 후 인덱스 반환

In [28]:
np.sort(arr)

array([2., 5., 5., 6.])

In [29]:
np.argsort(arr)

array([0, 2, 3, 1])